http:
  port: 8083
redis:
  host: 172.17.0.1
kafka:
  bootstrap-servers: 172.17.0.1:29092
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  restaurante-topic: Restaurantes
  pedido-criado-topic: PedidoCriado
  pedido-confirmado-topic: PedidoConfirmado
  pedido-recusado-topic: PedidoRecusado
  recusar-pedido-topic: RecusarPedido
  pedido-pendente-pagamento-topic: PedidoPendentePagamento
  verificar-timeout-pedido-topic: VerificarTimeoutPedidos
