http:
  port: 8082
redis:
  host: 172.17.0.1
kafka:
  bootstrap-servers: 172.17.0.1:29092
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  restaurante-topic: Restaurantes
  produto-topic: Produtos
