package br.com.diegoalexandro.ifood.pedidos_command.events;

public enum Eventos {
  RESTAURANTE_RECEBIDO,
  NOVO_PEDIDO,
  SALVAR_PEDIDO,
  ENVIAR_PEDIDO_CRIADO,
  VERIFICAR_PEDIDO_CONFIRMADO,
  PEDIDO_CONFIRMADO,
  ENVIAR_PEDIDO_CONFIRMADO;
}
